pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Which environment to deploy in?", name: "deployEnv")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "WhATS az?", name: "azDeploy")
        booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT?", name: "confirmDeploy")
    }

    stages {
        stage("Demo"){
            steps {
                echo "String is set to: ${params.deployEnv} \n"
                echo "Choice is set to: ${params.azDeploy}\n" 
                echo "Boolean is set to: ${params.confirmDeploy} \n"
            }
        }
    }
}